version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SEaglePathways
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

  client:
    image: seaglepathways-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/app

  server:
    image: seaglepathways-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server:/app